projects:
  app:
    schemaPath: "schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4466"
  prisma:
    schemaPath: "generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
